import pandas as pd

from snakemake.utils import min_version
min_version("5.24.0")

configfile: "config/configfile.yaml"

print(config['essential'])
print(config['token'])

include: "rules/commons.smk"
include: "rules/mageck_count.smk"
include: "rules/mageck_mle.smk"
include: "rules/mageck_rra.smk"
include: "rules/bagel.smk"
include: "rules/crisphiermix.smk"
include: "rules/integration.smk"

rule all:
    input:
        get_pipeline_outputs  # see workflow/rules/commons.smk
