import pandas as pd

from snakemake.utils import min_version
min_version("5.24.0")

tsv = pd.read_csv(config['inputs']['tsv'], sep="\t")

include: "rules/commons.smk"
if "fastq" in tsv.columns or "bam" in tsv.columns:
    include: "rules/mageck_count.smk"
include: "rules/mageck_mle.smk"
include: "rules/differential_analysis.smk"
include: "rules/mageck_rra.smk"
include: "rules/bagel.smk"
include: "rules/gsea_like_analysis.smk"
include: "rules/crisphiermix.smk"
include: "rules/integration.smk"
include: "rules/mapping.smk"

rule all:
    input:
        get_pipeline_outputs  # see workflow/rules/commons.smk
