from snakemake.utils import min_version
min_version("5.24.0")

## MAGeCK subworkflow
subworkflow MAGeCK_workflow:
    workdir:
        "../../MAGeCK/"
    snakefile:
        "../../MAGeCK/workflow/Snakefile"
    configfile:
        "../../MAGeCK/config/configfile.yaml"

rule a:
    input:
        MAGeCK_workflow("mageck_output.txt")
    output: ...
    shell:  ...
